### ISSUE TITLE
Missing default angle types

### ISSUE THREAD

**Issue by hgandhi2411** [paulrobustelli/Force-Fields#6]
Hi Paul,

For a threonine at the N terminus (NTHR), angle types `N3 CT C8` and `HP CT C8` are missing. This could be coming from the fact that you have CB bonded to C8 ( [line 2814](https://github.com/paulrobustelli/Force-Fields/blob/68c6c40f61a5344e6df557aefe88e7ecd34829b4/Gromacs_FFs/a99SBdisp.ff/aminoacids.rtp#L2814) in aminoacids.rtp) as opposed to CB bonded to CT in [amber99SB](https://github.com/gromacs/gromacs/blob/6fff49f17a7a716451919691d689b0d621b981fe/share/top/amber99sb.ff/aminoacids.rtp#L2489). Was there a mistake in copying the structure perhaps? Or maybe the parameters missing? 

Thanks!

**Comment by paulrobustelli** [comment]
Hi Heta. 

C8 should only be different from CT for the purposes of assigning dihedrals specific THR, so to fix this we can just copy the relevant angle terms for CT and replace them with C8.  For example: 

 CT  C8  CT     1    109.500  334.720  ; Amber99Sb-disp
 CT  C8  H1     1    109.500  418.400  ; Amber99Sb-disp
 CT  C8  HC     1    109.500  418.400  ; Amber99Sb-disp

Are just duplicated from: 

 CT  CT  CT     1    109.500  334.720  ; Amber99Sb-disp
 CT  CT  HC     1    109.500  418.400  ; Amber99Sb-disp
 CT  CT  H1     1    109.500  418.400  ; Amber99Sb-disp

So for N3 CT C8 and HP CT C8 

we would take: 
 CT  CT  N3     1    111.200  669.440  ; Amber99Sb-disp
 CT  CT  HP     1    109.500  418.400  ; Amber99Sb-disp

and duplicate them in ffbonded.itp as: 
 C8  CT  N3     1    111.200  669.440  ; Amber99Sb-disp
 C8  CT  HP     1    109.500  418.400  ; Amber99Sb-disp

Let me know if that works locally and I can add the terms in the repo.

**Comment by hgandhi2411** [comment]
Hi Paul, that solution worked for me, thank you!
